version: "3.9"
services:
  code-server-js:
    build:
      context: .
      dockerfile: docker/Dockerfile.javascript
    ports:
      - "8666:8080"
    volumes:
      - .:/home/coder/project
    environment:
      - PASSWORD=secret
    container_name: vscode-js-dev
