version: "3.9"
services:
  code-server-java:
    build:
      context: .
      dockerfile: docker/Dockerfile.java
    ports:
      - "8443:8080"
    volumes:
      - .:/home/coder/project
    environment:
      - PASSWORD=secret
    container_name: vscode-java-dev
